### ISSUE TITLE
IndexError: boolean index did not match indexed array along dimension 0;

### ISSUE THREAD

**Issue by EmmaAxe** [engeir/volcano-cooking#20]
### Issue
I get the following error when trying to run `poetry run volcano-cooking -o`. 
` File "/Users/emmaaxe/Documents/CESM/volcanocooking/src/volcano_cooking/modules/convert/adjust_emissions_and_heights.py", line 46, in adjust_altitude_range
miihs[miihs[idx] > 18] = 18
IndexError: boolean index did not match indexed array along dimension 0; dimension is 3000 but corresponding boolean dimension is 104`

### Needed files for: Option 1 (directly change forcing file)
I downloaded the file with 
`No forcing file found in /Users/emmaaxe/Documents/CESM/volcano-cooking/data/originals.
Do you want to download the original forcing file? (2.2GB) [y/N]: y`
`100% [....................................................................] 2279348216 / 2279348216Generating with 'GenerateRandomNormal'...`
I have also downloaded the needed coordinate file `fv_1.9x2.5.nc`

**Comment by EmmaAxe** [comment]
Thanks for the info! Unfortunately, still getting the error. Let me know if I need to provide further information.

``` python
$ poetry run volcano-cooking -o
Generating with 'GenerateRandomNormal'...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/emmaaxe/Library/Caches/pypoetry/virtualenvs/volcano-cooking-w0cgHmAi-py3.8/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/emmaaxe/Library/Caches/pypoetry/virtualenvs/volcano-cooking-w0cgHmAi-py3.8/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/emmaaxe/Library/Caches/pypoetry/virtualenvs/volcano-cooking-w0cgHmAi-py3.8/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/emmaaxe/Library/Caches/pypoetry/virtualenvs/volcano-cooking-w0cgHmAi-py3.8/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/emmaaxe/Documents/CESM/volcano-cooking/src/volcano_cooking/__main__.py", line 95, in main
    sv.create_volcanoes(
  File "/Users/emmaaxe/Documents/CESM/volcano-cooking/src/volcano_cooking/synthetic_volcanoes.py", line 82, in create_volcanoes
    frc_cls.make_dataset()
  File "/Users/emmaaxe/Documents/CESM/volcano-cooking/src/volcano_cooking/modules/create/rewrite_frc_file.py", line 73, in make_dataset
    self.miihs, self.mxihs = convert.adjust_altitude_range(
  File "/Users/emmaaxe/Documents/CESM/volcano-cooking/src/volcano_cooking/modules/convert/adjust_emissions_and_heights.py", line 46, in adjust_altitude_range
    miihs[miihs[idx] > 18] = 18
IndexError: boolean index did not match indexed array along dimension 0; dimension is 3000 but corresponding boolean dimension is 91
```
``` python
 $ poetry version                      
volcano-cooking 0.5.3
```

**Comment by engeir** [comment]
I forgot to mention that you should be on the `fix-array-indexing-for-adjust-alt-range` branch, in case that is the issue.

Could you try the following:

```sh
git pull
git checkout fix-array-indexing-for-adjust-alt-range
poetry run volcano-cooking -o
```

**Comment by engeir** [comment]
Great! I'll merge the PR then, and delete the branch.
